nameOverride: ""
fullnameOverride: ""

imagePullSecretName: cr-autra-cn-beijing

clusterName: ""

sourceController:
  enabled: true

controllerManager:
  replicas: 2
  image:
    repository: "autra-cn-beijing.cr.volces.com/autra/admiralty-agent"
    tag: "" # (default: .Chart.AppVersion)
    pullPolicy: IfNotPresent
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  nodeSelector: {}
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  affinity: {}
  tolerations: []

scheduler:
  replicas: 2
  image:
    repository: "autra-cn-beijing.cr.volces.com/autra/admiralty-scheduler"
    tag: "" # (default: .Chart.AppVersion)
    pullPolicy: IfNotPresent
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  nodeSelector: {}
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  affinity: {}
  tolerations: []

postDeleteJob:
  image:
    repository: "autra-cn-beijing.cr.volces.com/autra/admiralty-remove-finalizers"
    tag: "" # (default: .Chart.AppVersion)
    pullPolicy: IfNotPresent
  nodeSelector: {}
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  affinity: {}
  tolerations: []

restarter:
  replicas: 2
  image:
    repository: "autra-cn-beijing.cr.volces.com/autra/admiralty-restarter"
    tag: "" # (default: .Chart.AppVersion)
    pullPolicy: IfNotPresent
  nodeSelector: {}
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  affinity: {}
  tolerations: []

debug:
  controllerManager: false
  proxyScheduler: false
  candidateScheduler: false
  restarter: false

webhook:
  reinvocationPolicy: Never